// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHnXIoqc1jB7BOK5W2N85TvDWjnzWoguM',
    appId: '1:159774572464:web:d8ac4b0859646b2976a075',
    messagingSenderId: '159774572464',
    projectId: 'bmi-calculator-f5f7f',
    authDomain: 'bmi-calculator-f5f7f.firebaseapp.com',
    storageBucket: 'bmi-calculator-f5f7f.appspot.com',
    measurementId: 'G-WS5JZP33MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsU0wOU_IWteb3B59D3cGTCeK_w1iKaxc',
    appId: '1:159774572464:android:9ed3b13ef8dac2a076a075',
    messagingSenderId: '159774572464',
    projectId: 'bmi-calculator-f5f7f',
    storageBucket: 'bmi-calculator-f5f7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqI_j1Pqag8x6NlX4gdUzTcTZQUkoVZmw',
    appId: '1:159774572464:ios:bf45571334fecf4776a075',
    messagingSenderId: '159774572464',
    projectId: 'bmi-calculator-f5f7f',
    storageBucket: 'bmi-calculator-f5f7f.appspot.com',
    iosBundleId: 'com.shazlycode.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqI_j1Pqag8x6NlX4gdUzTcTZQUkoVZmw',
    appId: '1:159774572464:ios:fa901fcc94e2c5dd76a075',
    messagingSenderId: '159774572464',
    projectId: 'bmi-calculator-f5f7f',
    storageBucket: 'bmi-calculator-f5f7f.appspot.com',
    iosBundleId: 'com.shazlycode.bmi.RunnerTests',
  );
}
